group: edge
language: go
sudo: required

go_import_path: github.com/ahmedkamals/colorize

git:
  depth: 18

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

env:
  global:
    - secure: "UQQY/DoT1G8YmhLcKBMTl8dMMScAge9WcKU3886mL3/h4CDRpEHRurv1W/c8zdG4Wzntmg4dW83ZODfO4UBd9z7nP1JaLXC/c3tFmOFuQ9CRg9TPnHWv+8J8tLbY4rC2YSFZvp0xECnH5SvvqEc+J66FQaHm0rvXRlm0g0kmmejLoRUdXsL2LfWISmTvtmRMBoXORZZWF0t23GX/XLacjAFPgMzYBWxSLZFAs3BBvN1G2iD767RyONIiUtz/hsxAXOTqySpSrPJr0I93Re1B/vcmSgFYXYJkfNGWg4/+iYjUGA18F9I7w/R2U0eYyBytPcHCYWh1hlv7lpbiyoVEl5SuJXrsTyicbfSXsBZm2GyIUdvaYAxnTEWtPtoZPZY3y0f//oBAJzHtWlZF4wEyO55ft7+mwG11T5sA/qo/sEiTUl02uVXnre1ixslJyRUSRzRanwQnNy0ZpwLA0VwL4PYY0APijMIOroYTTmU4Ce7HEyXBJ0kl4yNAfiamxg+AMbUsnMyQiviXCIsBeBB43VCod4MWEBv3JKu3NgUtUAnV0MFzgsNUqlZqEz1wFoUoSS4ECZOqnacjroA85tlM7d6eUvYFtFEs8CimlyeG+AzW4JsYCs5SjBLZPwL3GFW7SxsyKpK5509gP1kBDW/VFVvwpVwAVvWtEDGOpP9bI10="
    - BUILD=false
    - GO111MODULE=on

branches:
  only:
    # Pushes and PR to the master branch
    - master
    # IMPORTANT Ruby regex to match tags. Required, or travis won't trigger deploys when a new tag
    # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+\.\d+.*$/

jobs:
  include:
    - stage: Coverage
      go: 1.13
      env: COVERAGE=true
      install:
        - make get-deps
    - &integration-tests
      stage: Integration tests
      go: 1.13.x
      os: linux
      env:
        - Build=true
        - INTEGRATION=true
    - <<: *integration-tests
      os: osx
    - <<: *integration-tests
      go: tip
    - <<: *integration-tests
      go: tip
      os: osx

before_install:
   - bash ./.travis/install.sh

install:
  - make go-install

script:
  # This to fix the error "fatal: ref HEAD is not a symbolic ref", that appears after every make call.
  - git checkout -b build-${TRAVIS_PULL_REQUEST}
  - if [ "$BUILD" == true ]; then make build; else echo 'skipping build.'; fi
  - if [ "$COVERAGE" == true ]; then make cover; travis_retry make coverage-send || true; else echo 'skipping coverage.'; fi
  - if [ "$INTEGRATION" == true ]; then make integration; else echo 'skipping integratoin tests.'; fi

after_success:
  - make nuke
  - echo "TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}"
  - echo "TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}"
  - echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}"

notifications:
  email:
      on_success: change
      on_failure: always
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/c3204ae99e4ce2c8a2fe
      on_success: change  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: never     # options: [always|never|change] default: always
